### ISSUE TITLE
[regression] compile failure v4l2 caused by #421

### ISSUE THREAD

**Issue by uartie** [01org/libyami#428]
Pull #421 causes compile regression...

```
./autogen.sh --enable-debug --enable-h264enc --enable-jpegenc --enable-vp8enc
  --enable-h265enc --enable-h264dec --enable-jpegdec --enable-vp8dec
  --enable-vp9dec --enable-h265dec --disable-fakedec --disable-capi
  --enable-tests --enable-v4l2 --enable-v4l2-glx --enable-dmabuf
  --enable-x11 --enable-avformat --disable-docs
```

```
v4l2_decode.cpp: In member function 'virtual bool V4l2Decoder::start()':
v4l2_decode.cpp:133:32: error: 'm_drmfd' was not declared in this scope
nativeDisplay.handle = m_drmfd;
^
Makefile:560: recipe for target 'libyami_v4l2_la-v4l2_decode.lo' failed
```

**Comment by xuguangxin** [comment]
seems too much build option for us...

**Comment by uartie** [comment]
This should simplify my point:

```
./autogen.sh --enable-v4l2-glx
```

**Comment by xuguangxin** [comment]
glx it for old chrome os, we can simply remove it.

**Comment by xuguangxin** [comment]
let me do this

**Comment by xuguangxin** [comment]
fix by https://github.com/01org/libyami/pull/429
