### ISSUE TITLE
H265 Decoder Fails to Compile with g++ (GCC) 5.1.1 and -fpermissive

### ISSUE THREAD

**Issue by uartie** [01org/libyami#334]
The following compile error occurs when compiling vaapidecoder_h265.cpp with g++ version 5.1.1 (this is the minimum version provided with Fedora 22).  With g++ version 4.9.2, the same compile error occurs unless ```-fpermissive``` is in the compiler flags.  This compiler flag is specified in all the libyami Makefile.am files, so the compilation works with g++ 4.9.2 by default.  However, this same compiler flag has no effect on eradicating this error when using g++ 5.1.1.

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I.. -I../interface -I../common -I../vaapi -I../codecparsers -I/home/uartie/Work/media/install/include -I/home/uartie/Work/media/install/include -fpermissive -I/home/uartie/Work/media/install/include -I/home/uartie/Work/media/install/include -g3 -MT libyami_decoder_la-vaapidecoder_h265.lo -MD -MP -MF .deps/libyami_decoder_la-vaapidecoder_h265.Tpo -c vaapidecoder_h265.cpp  -fPIC -DPIC -o .libs/libyami_decoder_la-vaapidecoder_h265.o
In file included from /usr/include/c++/5.1.1/algorithm:62:0,
from vaapidecoder_h265.cpp:38:
/usr/include/c++/5.1.1/bits/stl_algo.h: In instantiation of '_ForwardIterator std::__remove_if(_ForwardIterator, _ForwardIterator, _Predicate) [with _ForwardIterator = std::_Rb_tree_const_iterator<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265> >; _Predicate = __gnu_cxx::__ops::_Iter_pred<bool (*)(const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>&)>]':
/usr/include/c++/5.1.1/bits/stl_algo.h:936:30:   required from '_FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = std::_Rb_tree_const_iterator<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265> >; _Predicate = bool (*)(const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>&)]'
vaapidecoder_h265.cpp:280:76:   required from here
/usr/include/c++/5.1.1/bits/stl_algo.h:868:23: error: no match for 'operator=' (operand types are 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>' and 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>')
*__result = _GLIBCXX_MOVE(*__first);
^
In file included from /usr/include/c++/5.1.1/tr1/memory:50:0,
from ../interface/VideoCommonDefs.h:29,
from ../interface/VideoDecoderDefs.h:28,
from ../interface/VideoDecoderInterface.h:27,
from vaapidecoder_base.h:27,
from vaapidecoder_factory.h:24,
from vaapidecoder_h265.cpp:31:
/usr/include/c++/5.1.1/tr1/shared_ptr.h:1031:9: note: candidate: std::tr1::shared_ptr<_Tp>& std::tr1::shared_ptr<_Tp>::operator=(const std::tr1::shared_ptr<_Tp1>&) [with _Tp1 = YamiMediaCodec::VaapiDecPictureH265; _Tp = YamiMediaCodec::VaapiDecPictureH265] <near match>
operator=(const shared_ptr<_Tp1>& __r) // never throws
^
/usr/include/c++/5.1.1/tr1/shared_ptr.h:1031:9: note:   passing 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>*' as 'this' argument discards qualifiers
/usr/include/c++/5.1.1/tr1/shared_ptr.h:1040:9: note: candidate: template<class _Tp1> std::tr1::shared_ptr<_Tp>& std::tr1::shared_ptr<_Tp>::operator=(std::auto_ptr<_Tp1>&) [with _Tp1 = _Tp1; _Tp = YamiMediaCodec::VaapiDecPictureH265]
operator=(std::auto_ptr<_Tp1>& __r)
^
/usr/include/c++/5.1.1/tr1/shared_ptr.h:1040:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/5.1.1/algorithm:62:0,
from vaapidecoder_h265.cpp:38:
/usr/include/c++/5.1.1/bits/stl_algo.h:868:23: note:   types 'std::auto_ptr<_Tp1>' and 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>' have incompatible cv-qualifiers
*__result = _GLIBCXX_MOVE(*__first);
^
In file included from /usr/include/c++/5.1.1/tr1/memory:50:0,
from ../interface/VideoCommonDefs.h:29,
from ../interface/VideoDecoderDefs.h:28,
from ../interface/VideoDecoderInterface.h:27,
from vaapidecoder_base.h:27,
from vaapidecoder_factory.h:24,
from vaapidecoder_h265.cpp:31:
/usr/include/c++/5.1.1/tr1/shared_ptr.h:985:11: note: candidate: std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>& std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>::operator=(const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>&) <near match>
class shared_ptr
^
/usr/include/c++/5.1.1/tr1/shared_ptr.h:985:11: note:   passing 'const std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH265>*' as 'this' argument discards qualifiers
Makefile:617: recipe for target 'libyami_decoder_la-vaapidecoder_h265.lo' failed
make[2]: *** [libyami_decoder_la-vaapidecoder_h265.lo] Error 1
```

**Comment by uartie** [comment]
Here is a minimal/generic c++ example that exposes this compile error; perhaps we need to file this as an upstream compiler bug... but in the meantime libyami still needs some kind of workaround/fix:

```c++
// file simple.cpp
#include <tr1/memory>
#include <algorithm>
#include <set>

typedef std::tr1::shared_ptr<int> MyShared;
typedef std::set<MyShared> MySet;

inline bool isLessThan0(const MyShared& shared)
{
  return *shared < 0;
}

int main(int argc, char** argv)
{
  MySet my_set;
  for (int i(-10); i <= 10; ++i)
    my_set.insert(MyShared(new int(i)));

  MySet::iterator it = std::remove_if(
    my_set.begin(), my_set.end(), isLessThan0);
  my_set.erase(it, my_set.end());

  return 0;
}
```

With g++ 4.9.2:
 ```g++ -o simple simple.cpp``` - Does NOT Compile
 ```g++ -fpermissive -o simple simple.cpp``` - Compiles

With g++ 5.1.1
 ```g++ -o simple simple.cpp``` - Does NOT Compile
 ```g++ -fpermissive -o simple simple.cpp``` - Does NOT Compile

**Comment by uartie** [comment]
Ok, this post explains why you can't use std::remove_if on a std::set:

http://stackoverflow.com/questions/11141651/why-cant-i-remove-a-string-from-a-stdset-with-stdremove-if

... thus, this is strictly a libyami bug.

**Comment by uartie** [comment]
The fix is to use the std::set::erase method instead.

**Comment by chivakker** [comment]
I have seen other problems when updating to Fedora22, in particular an h.264 compilation issue.  In my experience with that patch was to also test the solution on Ubuntu so that there's no problem with older versions of gcc.  I also initially thought it would be a compiler issue but then I realized it was something to be fixed on libyami. 

My $0.02 anyways.

**Comment by uartie** [comment]
@chivakker would you be able to verify #335 works for you on Ubuntu?

**Comment by chivakker** [comment]
@uartie, I did on the patch series.

**Comment by uartie** [comment]
@chivakker thank you!

**Comment by xuguangxin** [comment]
sorry for my mistake. thanks for you guys.
