### ISSUE TITLE
Bug: Cannot build on Ubuntu 16.04LTS: header file va/va_enc.h missing.

### ISSUE THREAD

**Issue by Brainiarc7** [01org/libyami#748]
Hello,

The build fails with:

```
In file included from vaapiencpicture.cpp:26:0:
/usr/local/include/va/va_intel_fei.h:39:23: fatal error: va/va_enc.h: No such file or directory
compilation terminated.
Makefile:672: recipe for target 'libyami_encoder_la-vaapiencpicture.lo' failed
make[2]: *** [libyami_encoder_la-vaapiencpicture.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
vaapiencoder_h264.cpp: In member function ‘virtual YamiStatus YamiMediaCodec::VaapiEncoderH264::getMVBufferSize(uint32_t*)’:
vaapiencoder_h264.cpp:1090:20: error: ‘VAMotionVectorIntel’ was not declared in this scope
     *Size = sizeof(VAMotionVectorIntel)*16*m_mbWidth*m_mbHeight;
                    ^
Makefile:693: recipe for target 'libyami_encoder_la-vaapiencoder_h264.lo' failed
make[2]: *** [libyami_encoder_la-vaapiencoder_h264.lo] Error 1
make[2]: Leaving directory '/home/lin/source.build/libyami/encoder'
Makefile:681: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/lin/source.build/libyami'
Makefile:510: recipe for target 'all' failed
make: *** [all] Error 2
```

The package is referring to a header file `va/va_enc.h` which does not exist on the system:

```
dpkg -L libva-dev
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libva-dev
/usr/share/doc/libva-dev/README.Debian
/usr/share/doc/libva-dev/changelog.gz
/usr/share/doc/libva-dev/changelog.Debian.gz
/usr/share/doc/libva-dev/copyright
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libva-glx.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libva-tpi.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libva-drm.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libva.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libva-egl.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libva-x11.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libva-wayland.pc
/usr/include
/usr/include/va
/usr/include/va/va_backend_wayland.h
/usr/include/va/va_compat.h
/usr/include/va/va_backend_glx.h
/usr/include/va/va_dricommon.h
/usr/include/va/va_backend_egl.h
/usr/include/va/va_enc_vp8.h
/usr/include/va/va_glx.h
/usr/include/va/va_drmcommon.h
/usr/include/va/va_dec_vp8.h
/usr/include/va/va_dec_hevc.h
/usr/include/va/va_dri2.h
/usr/include/va/va_enc_hevc.h
/usr/include/va/va.h
/usr/include/va/va_enc_vp9.h
/usr/include/va/va_backend.h
/usr/include/va/va_version.h
/usr/include/va/va_enc_h264.h
/usr/include/va/va_enc_mpeg2.h
/usr/include/va/va_backend_vpp.h
/usr/include/va/va_wayland.h
/usr/include/va/va_dec_vp9.h
/usr/include/va/va_backend_tpi.h
/usr/include/va/va_drm.h
/usr/include/va/va_egl.h
/usr/include/va/va_x11.h
/usr/include/va/va_tpi.h
/usr/include/va/va_dec_jpeg.h
/usr/include/va/va_vpp.h
/usr/include/va/va_enc_jpeg.h
/usr/lib/x86_64-linux-gnu/libva-egl.so
/usr/lib/x86_64-linux-gnu/libva-drm.so
/usr/lib/x86_64-linux-gnu/libva-glx.so
/usr/lib/x86_64-linux-gnu/libva-wayland.so
/usr/lib/x86_64-linux-gnu/libva-x11.so
/usr/lib/x86_64-linux-gnu/libva-tpi.so
/usr/lib/x86_64-linux-gnu/libva.so


```

Also, with the libva package built from source:

```
ls -al /usr/local/include/va/
total 428
drwxr-xr-x  2 root root   4096 Jun 22 01:48 .
drwxr-xr-x 10 root root   4096 Jun  3 06:58 ..
-rw-r--r--  1 root root   1601 Jun 22 01:48 va_backend_egl.h
-rw-r--r--  1 root root   2040 Jun 22 01:48 va_backend_glx.h
-rw-r--r--  1 root root  15029 Jun 22 01:48 va_backend.h
-rw-r--r--  1 root root   2253 Jun 22 01:48 va_backend_tpi.h
-rw-r--r--  1 root root   2205 Jun 22 01:48 va_backend_vpp.h
-rw-r--r--  1 root root   2461 Jun 22 01:48 va_backend_wayland.h
-rw-r--r--  1 root root   4067 Jun 22 01:48 va_compat.h
-rw-r--r--  1 root root  17674 Jun 22 01:48 va_dec_hevc.h
-rw-r--r--  1 root root   5026 Jun 22 01:48 va_dec_jpeg.h
-rw-r--r--  1 root root   8345 Jun 22 01:48 va_dec_vp8.h
-rw-r--r--  1 root root  11868 Jun 22 01:48 va_dec_vp9.h
-rw-r--r--  1 root root   2848 Jun 22 01:48 va_dri2.h
-rw-r--r--  1 root root   3076 Jun 22 01:48 va_dricommon.h
-rw-r--r--  1 root root   2970 Jun 22 01:48 va_drmcommon.h
-rw-r--r--  1 root root   1776 Jun 22 01:48 va_drm.h
-rw-r--r--  1 root root    510 Jun 22 01:48 va_egl.h
-rw-r--r--  1 root root  23704 Jun 22 01:48 va_enc_h264.h
-rw-r--r--  1 root root  29450 Jun 22 01:48 va_enc_hevc.h
-rw-r--r--  1 root root   4743 Jun 22 01:48 va_enc_jpeg.h
-rw-r--r--  1 root root  10535 Jun 22 01:48 va_enc_mpeg2.h
-rw-r--r--  1 root root  11712 Jun 22 01:48 va_enc_vp8.h
-rw-r--r--  1 root root  22523 Jun 22 01:48 va_enc_vp9.h
-rw-r--r--  1 root root   3359 Jun 22 01:48 va_glx.h
-rw-r--r--  1 root root 120849 Jun 22 01:48 va.h
-rw-r--r--  1 root root  12106 Jun 22 01:37 va_intel_fei.h
-rw-r--r--  1 root root   7477 Jun 22 01:38 va_intel_statistics.h
-rw-r--r--  1 root root   3893 Jun 22 01:48 va_tpi.h
-rw-r--r--  1 root root   2658 Jun 22 01:48 va_version.h
-rw-r--r--  1 root root  29208 Jun 22 01:48 va_vpp.h
-rw-r--r--  1 root root   4258 Jun 22 01:48 va_wayland.h
-rw-r--r--  1 root root   2194 Jun 22 01:48 va_x11.h



```

Seems like a bug. Please fix.

**Comment by chivakker** [comment]
What are you compiling? It looks like your setup contains files that don't belong to this project.  Can you confirm you're compiling this project?

**Comment by xuguangxin** [comment]
Hi @Brainiarc7 ,
do you really need to get mv from encoder output? If not you can remove "--enable-get-mv"from you autogen command line.
thanks

**Comment by Brainiarc7** [comment]
Hey,

I think I know what the problem is. The --enable-get-mv bits.

Retesting,

**Comment by xuguangxin** [comment]
@Brainiarc7 , glad to know this, please ping us if you have any other issue.

**Comment by xuguangxin** [comment]
close this since it fixed
