### ISSUE TITLE
Libyami fails to compile on GCC 7.1.1

### ISSUE THREAD

**Issue by stripes416** [01org/libyami#776]
```
22:29:39,668 INFO  - vaapipostprocess_scaler_unittest.cpp: In static member function 'static void YamiMediaCodec::VaapiPostProcessScalerTest::checkColorBalanceFilter(YamiMediaCodec::VaapiPostProcessScaler&, VppColorBalanceMode)':
22:29:39,668 INFO  - vaapipostprocess_scaler_unittest.cpp:110:12: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=dangling-else]
22:29:39,668 INFO  - if (COLORBALANCE_NONE != mode)
22:29:39,668 INFO  - ^
```

**Comment by uartie** [comment]
This is a side-effect from the GTEST macros not enclosing the entire macro definition inside braces.  We should only have to add braces in our **if** statement to fix this (e.g. **if(...) { ... }**)

**Comment by xuguangxin** [comment]
Hi @stripes416 , 
could you help prepare a patch for this?

**Comment by uartie** [comment]
https://github.com/google/googletest/issues/1119
