### ISSUE TITLE
Build failure with ffmpeg 4.0

### ISSUE THREAD

**Issue by sebastinas** [01org/libyami#841]
libyami's examples do not build with ffmpeg 4.0:
```
make[3]: Entering directory '/<<PKGBUILDDIR>>/examples'
g++ -DHAVE_CONFIG_H -I. -I..  -I../tests -I/usr/include/libyami  -I..   -D__STDC_CONSTANT_MACROS -I/usr/include/x86_64-linux-gnu -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -Wall -Wno-unused-function -Wno-cpp -Wno-missing-braces -Werror -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -c -o ../tests/decodeinputavformat.o ../tests/decodeinputavformat.cpp
../tests/decodeinputavformat.cpp: In constructor 'DecodeInputAvFormat::DecodeInputAvFormat()':
../tests/decodeinputavformat.cpp:32:21: error: 'void av_register_all()' is deprecated [-Werror=deprecated-declarations]
     av_register_all();
                     ^
In file included from ../tests/decodeinputavformat.h:22:0,
                 from ../tests/decodeinputavformat.cpp:20:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:621: ../tests/decodeinputavformat.o] Error 1
```

(forewarded from Debian's [#896825](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896825)).

**Comment by sebastinas** [comment]
Sorry for the noise. I missed that this was already fixed in libyami-utils.

**Comment by xuguangxin** [comment]
@sebastinas , no problem, thanks for report
